test: Fix cleanup of installed test packages
`TestUpdates.testBasic` previously left chocolate.rpm installed, as a
plain `rpm -e` failed:

    error: Failed dependencies:
            chocolate is needed by (installed) vanilla-1.0-2.noarch

Use `--nodeps` option to force the removal, so that we don't have to do
it in a particular order.

Cherry-picked from master commit da8512d34.