test: Fix formatting of timeout messages
Commit fe1274d79 inadvertently changed the formatting of timeout
messages from

  Error: timeout
  blabla

to

  Error: timeoutblabla

as the previous messages string always got a `\n` prepended. Add  it
back. This will still cause an extra newline if there is no message, but
this is fairly harmless.

This unbreaks all our naughty patterns that involve timeouts.

Closes #7160
Reviewed-by: Dominik Perpeet <dperpeet@redhat.com>