test: Fix waiting for kubernetes
`svc/kubernetes` got renamed to `service/kubernetes` in the most recent
version. This causes `wait_api_server()` to always run through the full
retry loop. As the loop was also not checking for success in the end,
this was a race condition between the loop timeout and the
`Machine.execute()` timeout. So accept both spellings for now, and
properly fail on timeout.

This uncovered a wrong invocation of `wait_api_server()` in
`check-kubernetes TestConnection.testConnect`: There it gets configured
to only listen on 10.111.113.1, not localhost, so the wait loop will
never be successful. Specifying `host` also doesn't work, as `kubectl
get all` still fails with

    error: the server doesn't have a resource type "cronjobs"

In Fedora ≥ 27, kube-apiserver.service now properly waits for the
service to actually be available [1], we don't actually need to wait and
thus this can just be dropped.

The same "wrong address" issue hits the container/kubernetes test, fix
it there. While this runs on Fedora 26, just do a static one-minute
sleep hack instead, which effectively is what the previous broken
`wait_api_server()` did. This will go away with PR #9172.

Closes #9171

[1] https://github.com/kubernetes/kubernetes/issues/8311