test: Fix race condition in check-apps
`TestApps.testBasic` often fails like this:

    CalledProcessError: Command 'pkcon -y install appstream-data-test' returned non-zero exit status 7

because the running PackageKit still has some outdated internal state
after reconfiguring the repositories on disk. Stop it so that it
re-reads the state properly.

Closes #8907