test: Force checkout in github-task
Without this there are combinations of commits that cause all
the verify machines to eventually fail with:

error: The following untracked working tree files would be overwritten by checkout:

Closes #4370
Reviewed-by: Peter <petervo@redhat.com>