test: Wait for NetworkManager to be online before PackageKit operations
When trying `pkcon refresh` or similar operations, PackageKit fails with

    Fatal error: Cannot refresh cache whilst offline

while NetworkManager is still busy with setting up connections.

Wait until NetworkManager's connectivity is at least
`NM_CONNECTIVITY_LIMITED` [1], so that PackageKit is happy. (This is
unfortunately not what `nm-online` does.)

This is supposed to replace the ubuntu-stable specific hack with setting
a fake manual route. But this does not work because
/etc/NetworkManager/conf.d/noauto.conf is somehow missing from that
image, so that NetworkManager still forever tries to connect to the
disconnected eth1. Until this is fixed on the image, keep the hack in
place, but update its documentation.

[1] https://developer.gnome.org/NetworkManager/unstable/nm-dbus-types.html#NMConnectivityState

Closes #12715