websocket: Avoid -fanalyzer-null-dereference warning in send_prefixed_message_rfc6455()
When building with `-fanalyzer`, gcc does not recognize that the two
"use a mask" conditions in send_prefixed_message_rfc6455 are identical
and don't change in the intermediate code:

```
src/websocket/websocketconnection.c:356:20: error: dereference of NULL ‘0’ [CWE-476] [-Werror=analyzer-null-dereference]
  356 |     data[n] ^= mask[n & 3];
      |                ~~~~^~~~~~~
```

Pull them out into a common constant, and add an assertion to
xor_with_mask_rfc6455() to make sure that it does not get called with
NULL pointers.