build: Force `pip install` to not check for already installed module
This previously broke distro package builds when they happened with the
`cockpit-bridge` package installed:

```
Processing ./tmp/wheel/cockpit-0-py3-none-any.whl
Installing collected packages: cockpit
  Attempting uninstall: cockpit
    Found existing installation: cockpit 311
ERROR: Cannot uninstall cockpit 311, RECORD file not found. Hint: The package was installed by debian.
```

This is a `pip` bug (https://github.com/pypa/pip/issues/3063), work
around it with `--ignore-installed`.