shell: Fix crash on uninitialized superuser proxy Bridges
During superuser initialization it can happen that
`superuser_proxy.Bridges` does not exist yet. This made the shell crash
with

    TypeError: Cannot read properties of undefined (reading 'length')