ws: Fix memory leak in process_transport_authorize()
Spotted by coverity:

```
Error: RESOURCE_LEAK (CWE-772): [#def30]
cockpit-237/src/ws/cockpitwebservice.c:577: alloc_fn: Storage is returned from allocation function "cockpit_authorize_build_basic".
cockpit-237/src/ws/cockpitwebservice.c:577: var_assign: Assigning: "response" = storage returned from "cockpit_authorize_build_basic(cockpit_creds_get_user(self->creds), password)".
cockpit-237/src/ws/cockpitwebservice.c:589: noescape: Assuming resource "response" is not freed or pointed-to as ellipsis argument to "cockpit_transport_build_control".
cockpit-237/src/ws/cockpitwebservice.c:600: leaked_storage: Variable "response" going out of scope leaks the storage it points to.
```

Assign the result to `alloc` as well, like in the other branches that do
allocation, to make sure it eventually gets cleaned up.

Part of https://bugzilla.redhat.com/show_bug.cgi?id=1938693