test: Fix --sit with existing machines
Commit e318fb0778 botched the fix for the case that `machines` was
not provided. It's expected to be a dict, so actually fall back to a
dict, not a list (as it was before commit d0085da1cd5a5f). Fixes

```
  File "test/verify/check-system-realms", line 96, in testQualifiedUsers
    testlib.sit()
  File "main/test/common/testlib.py", line 2533, in sit
    for (_, machine) in (machines or []).items():
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
```