kubernetes: readme describes `bridge helper failed`
When ` test/vm-run --network openshift` is executed on Fedora or CentOS,
it failes with following error:

libvirt.libvirtError: internal error: process exited while connecting to monitor:
2017-08-10T14:46:59.118700Z qemu-system-x86_64: -chardev pty,id=charserial0:
char device redirected to /dev/pts/4 (label charserial0)
access denied by acl file
2017-08-10T14:46:59.126574Z qemu-system-x86_64: -netdev bridge,br=cockpit1,id=bridge0:
bridge helper failed

which is not entirely self-explanatory. Link to a explanation and
workaround added.