packagekit: Drop usage of D-Bus proxies
In most cases we don't require object properties or always subscribing
to their changes. We also never removed signal listeners from finished
transactions. The excessive D-Bus calls from the proxy seem to upset
PackageKit sometimes, resulting in failed calls to `GetUpdates()` or
`GetOldTransactions()`, such as `TypeError: undefined is not a function`.

Restructure `pkTransaction()` to accept a signal handler map and a
property change handler, and do the plumbing right in that function, as
it's the same for all kinds of PackageKit transactions. This allows us
to change/fix the transaction logic in one place.

Closes #7175