test: Fix parent import in check-openshift
So that this test can be run like all the others. Without this, it fails
with

    $ test/verify/check-openshift TestOpenshift.testConnect
    Traceback (most recent call last):
      File "test/verify/kubelib.py", line 27, in <module>
        import testlib
    ModuleNotFoundError: No module named 'testlib'