packagekit: Fix auto-updates detection script
Running `command -v` with multiple items is a bashism, and does not work
with POSIX shells like Debian/Ubuntu's dash (default shell). Thus
explicitly use bash.

This fixes

    warning: basename: missing operand

and the failure of the script

    error: automatic updates getBackend() detection failed: