docker: Fix filtering when image.RepoTags is null
This commit should fix this failure:

TypeError: null is not an object (evaluating 'e.RepoTags[0]')

Closes #5234
Reviewed-by: Lars Karlitski <lars@karlitski.net>