containers: Add explicit docker.io registry for unit-tests
Most recent podman resolves the short "debian" name to quay.io. But
https://quay.io/repository/i386/debian is not a thing, thus building the
i386 container fails now with

    Error: error creating build container: Error initializing source docker://quay.io/i386/debian:stable:
    Error reading manifest stable in quay.io/i386/debian: unauthorized: access to the requested resource is not authorized

Explicitly pull from docker.io to fix that.