webpack: Don't generate jquery.js and cockpit.js
For local development you can run `webpack` with `--watch` parameter
to have automatic syncing of changes done to source files.

However, this will also override `dist/base1/jquery.js` file with clean
upstream jquery.js that lacks tooltip from bootstrap and some other
merged plugins.  If you want to run `./test/verify/check-***` it will
fail with "RuntimeError: TypeError: r.tooltip is not a function".

Since commit <7d5232c0ca6199bb93d2857fa5fcaa9c8b99bc21> the direct
invocation of `webpack` was removed from `HACKING.md` and you should
always run `make` we can safely remove the generation.

This was reintroduced by commit <cb56b968be3727fe321ee870bbf95dc94b1e496c>.

Closes #10131