test: Fix issues with github-task check_publishing()
This checks whether the tests are still running as ourselves.
Fixes two issues. First when the process has already exited,
proc.terminate() was throwing:

OSError: [Errno 3] No such process

In addition fix cases check check_publishing() is called
more than once. Make it a no-op in the latter invocations.

Closes #3517

Reviewed-by: Dominik Perpeet <dperpeet@redhat.com>