Revert "test: Improve image pruning logic"
It breaks tests: `ImportError: cannot import name testinfra`

This reverts commit d284888b17d26d4daba5829d238785f0ceda6c12.